#!/bin/bash

# Test script to simulate daemon workflow and test PR creation
set -e

PROJECT_NAME="structric"
TARGET_DIR="/home/faz/development/structric"
BASE_DIR="/home/faz/development/ClaudeNightsWatch"
DAEMON_PID="test$$"
BRANCH_NAME="claude/test-pr-$DAEMON_PID"
GIT_WORKFLOW_ENABLED="true"

echo "=== Testing PR Creation Workflow ==="
echo "Project: $PROJECT_NAME"
echo "Target: $TARGET_DIR"
echo "Branch: $BRANCH_NAME"
echo

# Ensure we have the original branch file
if [ ! -f "$BASE_DIR/logs/$PROJECT_NAME/original-branch" ]; then
    echo "ERROR: No original-branch file found"
    exit 1
fi

ORIGINAL_BRANCH=$(cat "$BASE_DIR/logs/$PROJECT_NAME/original-branch" | tr -d '\n' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
echo "Original branch: $ORIGINAL_BRANCH"

# Go to target directory
cd "$TARGET_DIR" || exit 1

# Create test branch
echo "Creating test branch: $BRANCH_NAME"
git checkout -b "$BRANCH_NAME" 2>/dev/null || git checkout "$BRANCH_NAME" 2>/dev/null

# Make a test change
echo "Making test change..."
echo "# Test change by Claude Nights Watch $(date)" > nights-watch-test.md
git add nights-watch-test.md

# Commit the change
echo "Committing test change..."
git commit -m "Test commit for PR creation

This is a test commit to verify the PR creation workflow.
Daemon PID: $DAEMON_PID
Timestamp: $(date '+%Y-%m-%d %H:%M:%S UTC')

Co-Authored-By: Claude <noreply@anthropic.com>"

# Push to remote
echo "Pushing to remote..."
git push -u origin "$BRANCH_NAME" || echo "WARNING: Push failed, continuing..."

# Test PR creation logic (simulate daemon's create_pull_request function)
echo
echo "=== Testing PR Creation Logic ==="

# Get original branch for PR target
original_branch=""
if [ -f "$BASE_DIR/logs/$PROJECT_NAME/original-branch" ]; then
    original_branch=$(cat "$BASE_DIR/logs/$PROJECT_NAME/original-branch" 2>/dev/null | tr -d '\n' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
    if [ -z "$original_branch" ]; then
        echo "WARNING: original-branch file exists but is empty, falling back to main"
        original_branch="main"
    fi
else
    echo "WARNING: original-branch file not found, falling back to main"
    original_branch="main"
fi

echo "Creating PR with base branch: $original_branch"

# Check if gh CLI is available
if ! command -v gh >/dev/null 2>&1; then
    echo "gh CLI not available, skipping actual PR creation"
    echo "Would create PR: $original_branch <- $BRANCH_NAME"
    exit 0
fi

# Check if PR already exists
if gh pr list --head "$BRANCH_NAME" | grep -q "$BRANCH_NAME"; then
    echo "Pull request already exists for branch $BRANCH_NAME"
    gh pr list --head "$BRANCH_NAME"
    exit 0
fi

# Create the PR
pr_title="Claude Nights Watch: Test PR Creation (daemon $DAEMON_PID)"
pr_body="## Summary
This PR tests the enhanced Claude Nights Watch PR creation functionality.

**Project:** $PROJECT_NAME
**Daemon PID:** $DAEMON_PID
**Execution Time:** $(date '+%Y-%m-%d %H:%M:%S UTC')
**Branch:** $BRANCH_NAME
**Base Branch:** $original_branch

## Changes Made
This is a test PR to verify that:
- ✅ Branch is created from the current working branch (not main)
- ✅ PR targets the correct base branch (not hardcoded main)
- ✅ Branch is pushed to remote
- ✅ PR is created successfully

## Test Plan
- [x] Create test branch from current branch
- [x] Make test commit
- [x] Push branch to remote
- [x] Create PR with correct base branch

🤖 Generated by Claude Nights Watch daemon test
Co-Authored-By: Claude <noreply@anthropic.com>"

echo "Creating PR..."
if gh pr create --title "$pr_title" --body "$pr_body" --base "$original_branch" --head "$BRANCH_NAME"; then
    echo "✅ Successfully created pull request"
    # Get PR URL for display
    pr_url=$(gh pr list --head "$BRANCH_NAME" --json url --jq '.[0].url')
    echo "PR URL: $pr_url"
else
    echo "❌ Failed to create pull request"
    exit 1
fi

echo
echo "=== Test Complete ==="
echo "Branch: $BRANCH_NAME"
echo "Original branch: $ORIGINAL_BRANCH"
echo "PR base: $original_branch"
